# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160406_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='year',
            field=models.PositiveIntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='season',
            field=models.CharField(choices=[('sp', 'Spring'), ('su', 'Summer'), ('fa', 'Fall'), ('wi', 'Winter')], max_length=20),
        ),
    ]
