# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-13 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170713_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(related_name='items', to='menu.Ingredient'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='menus', to='menu.Item'),
        ),
    ]
