# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20170713_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='season',
            field=models.SmallIntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Fall'), (4, 'Winter')]),
        ),
    ]
